# Generated by Django 5.1.2 on 2024-10-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('autor', models.CharField(max_length=50)),
                ('co_autor', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=30)),
                ('disponível', models.BooleanField(default=True)),
            ],
        ),
    ]
