# Generated by Django 5.1.2 on 2024-11-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('autor', models.CharField(max_length=50)),
                ('co_autor', models.CharField(blank=True, max_length=50)),
                ('disponivel', models.BooleanField(default=False)),
                ('exemplares', models.FloatField(default=0)),
                ('capa_url', models.URLField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Livro',
            },
        ),
    ]
