# Generated by Django 5.1.2 on 2024-10-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='exemplares',
            field=models.FloatField(default=1),
        ),
    ]
