# Generated by Django 5.1.2 on 2024-10-22 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0004_categoria_livros_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livros',
            name='genero',
        ),
    ]
