# Generated by Django 5.1.2 on 2024-10-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0005_remove_livros_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='categoria',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
