# Generated by Django 5.1.2 on 2024-11-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0006_alter_livros_categoria_delete_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='capa_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livros',
            name='disponível',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='livros',
            name='exemplares',
            field=models.FloatField(default=0),
        ),
    ]
