# Generated by Django 5.1.2 on 2024-11-07 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0007_livros_capa_url_alter_livros_disponível_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livros',
            old_name='disponível',
            new_name='disponivel',
        ),
    ]
