# Generated by Django 5.1.2 on 2024-11-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0008_rename_disponível_livros_disponivel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livros',
            old_name='disponivel',
            new_name='disponível',
        ),
        migrations.AddField(
            model_name='livros',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
