# Generated by Django 5.1.2 on 2024-11-07 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0009_rename_disponivel_livros_disponível_livros_descricao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livros',
            old_name='disponível',
            new_name='disponivel',
        ),
    ]
